// Catalog access layer. Data is generated by scripts/scapemusic-sync-catalog.py
// from apps/beatscape/public/catalog.json — the single source of truth.

import data from "../data/catalog.json";

export type Vibe = "night-drive" | "groove" | "battle" | "chill";

export interface Track {
  track_id: string;
  title: string;
  artist: string;
  genre: string;
  bpm: number;
  vibe: Vibe;
  district: string;
  tags: string[];
  cover: string;
  og: string;
  stream_audio: string;
  stream_duration_sec: number;
  /** The Late Static call-in quote (optional, from trackRequests.json). */
  quote?: string;
}

export const TRACKS: Track[] = data as unknown as Track[];

const byId = new Map(TRACKS.map((t) => [t.track_id, t]));

export function trackById(id: string): Track | undefined {
  return byId.get(id);
}

export interface VibeMeta {
  id: Vibe;
  name: string;
  /** The Late Static radio column (World Bible §8) — playlist naming truth. */
  column: string;
  blurb: string;
  color: string;
}

export const VIBES: VibeMeta[] = [
  {
    id: "night-drive",
    name: "Night Drive",
    column: "Overnight Drive",
    blurb: "Steady wheel, rolling low end.",
    color: "#5b8def",
  },
  {
    id: "groove",
    name: "Groove",
    column: "Groove Hour",
    blurb: "Urban jazz with a fight in it. Brass first.",
    color: "#ffb020",
  },
  {
    id: "battle",
    name: "Battle",
    column: "Battle Call",
    blurb: "For blocks that refuse to go quiet.",
    color: "#e23d3d",
  },
  {
    id: "chill",
    name: "Chill",
    column: "Last Call",
    blurb: "The last hour before the city exhales.",
    color: "#f2e4c9",
  },
];

const vibeMetaById = new Map(VIBES.map((v) => [v.id, v]));

export function vibeMeta(vibe: Vibe): VibeMeta {
  return vibeMetaById.get(vibe) ?? VIBES[0];
}

export const GENRES: string[] = ["EDM", "Pop", "Hip-hop", "Rock", "R&B"];

export type SortKey = "catalog" | "title" | "artist" | "bpm" | "duration";

export interface FilterOpts {
  query?: string;
  vibe?: Vibe | "all";
  genre?: string | "all";
  sort?: SortKey;
}

export function filterTracks(opts: FilterOpts = {}): Track[] {
  const q = opts.query?.trim().toLowerCase();
  const list = TRACKS.filter((t) => {
    if (opts.vibe && opts.vibe !== "all" && t.vibe !== opts.vibe) return false;
    if (opts.genre && opts.genre !== "all" && t.genre !== opts.genre) return false;
    if (!q) return true;
    return (
      t.title.toLowerCase().includes(q) ||
      t.artist.toLowerCase().includes(q) ||
      t.district.toLowerCase().includes(q)
    );
  });
  const sorted = [...list];
  switch (opts.sort) {
    case "title":
      sorted.sort((a, b) => a.title.localeCompare(b.title));
      break;
    case "artist":
      sorted.sort((a, b) => a.artist.localeCompare(b.artist) || a.title.localeCompare(b.title));
      break;
    case "bpm":
      sorted.sort((a, b) => a.bpm - b.bpm);
      break;
    case "duration":
      sorted.sort((a, b) => b.stream_duration_sec - a.stream_duration_sec);
      break;
    default:
      break; // catalog order
  }
  return sorted;
}

/** Deep link into the BeatScape game chart for this track (5-1 loop, other way). */
export function gameTrackUrl(id: string): string {
  const base = import.meta.env.VITE_GAME_URL ?? "http://127.0.0.1:5175/beatscape";
  return `${base.replace(/\/+$/, "")}/track/${id}`;
}
